### ISSUE TITLE
undefined method `for_all_cops'  error with rubocop `0.39.0`

### ISSUE THREAD

**Issue by shortdudey123** [nevir/rubocop-rspec#78]
```
$ bundle exec rubocop --version
0.39.0
$ 
```

```
$ bundle exec rubocop -d
For /Users/user/github_project: configuration from /Users/user/github_project/.rubocop.yml
configuration from /Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-rspec-1.4.0/config/default.yml
undefined method `for_all_cops' for #<Hash:0x007fd33eb71038>
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:120:in `merge_with_default'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-rspec-1.4.0/lib/rubocop/rspec/inject.rb:17:in `defaults!'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-rspec-1.4.0/lib/rubocop-rspec.rb:9:in `<top (required)>'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:16:in `require'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:16:in `block in resolve_requires'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:12:in `each'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:39:in `load_file'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:97:in `configuration_from_file'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/config_store.rb:41:in `for'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/cli.rb:88:in `apply_default_formatter'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/lib/rubocop/cli.rb:26:in `run'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/bin/rubocop:14:in `block in <top (required)>'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/user/github_project/.bundle/ruby/2.2.0/gems/rubocop-0.39.0/bin/rubocop:13:in `<top (required)>'
/Users/user/github_project/.bundle/ruby/2.2.0/bin/rubocop:23:in `load'
/Users/user/github_project/.bundle/ruby/2.2.0/bin/rubocop:23:in `<main>'
Finished in 0.019039359060116112 seconds
$ 
```

**Comment by shortdudey123** [comment]
maybe due to hardcoding `0.37.2`?
https://github.com/nevir/rubocop-rspec/commit/9f892f776c35cf659eb1bd6caecc59862b1782cb#diff-78af005654c8581d6d1c63eee4e637a4R33

**Comment by olliebennett** [comment]
I'm also seeing this. Also occurs for Rubocop version `0.38.0`.

**Comment by olliebennett** [comment]
And I don't believe it's caused by the hardcoded gemspec dependency; I tested relaxing that dependency with no effect:

```ruby
gem 'rubocop-rspec', group: [:development, :test], git: 'https://github.com/olliebennett/rubocop-rspec', branch: 'relax-rubocop-dependency'
```

Guess it's an incompatibility somewhere else.

**Comment by shortdudey123** [comment]
@olliebennett thanks for chiming in :)
I also tested relaxing the dependency and that did not help me either

**Comment by dankohn** [comment]
The same issue is referenced here on Rubocop: https://github.com/bbatsov/rubocop/issues/2965

I'm unclear whether there is a fix that can be done here or whether Rubocop needs to change.
